// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/testSrv/testSrv.proto

package go_micro_srv_testSrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for TestSrv service

type TestSrvService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type testSrvService struct {
	c    client.Client
	name string
}

func NewTestSrvService(name string, c client.Client) TestSrvService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.testSrv"
	}
	return &testSrvService{
		c:    c,
		name: name,
	}
}

func (c *testSrvService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TestSrv.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TestSrv service

type TestSrvHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterTestSrvHandler(s server.Server, hdlr TestSrvHandler, opts ...server.HandlerOption) error {
	type testSrv interface {
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type TestSrv struct {
		testSrv
	}
	h := &testSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&TestSrv{h}, opts...))
}

type testSrvHandler struct {
	TestSrvHandler
}

func (h *testSrvHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.TestSrvHandler.Call(ctx, in, out)
}
